language: c
os: linux
dist: focal
arch: ppc64le

addons:
  apt:
    sources:
    - sourceline: 'ppa:wileamyp/exciting-plus-deps'
    update: true
    packages:
    - gfortran
    - flang-7
    - libopenmpi-dev
    - libopenblas-openmp-dev
    - libhdf5-dev
    - libfftw3-dev

before_install:
- test -n $CC && unset CC

install: skip

jobs:
  include:
  - stage: build
    compiler: gcc
    name: "Build Exciting-Plus, CPU-only version, on ppc64le with GCC"
    env: COMP="gcc"
  - compiler: clang
    name: "Build Exciting-Plus, CPU-only version, on ppc64le with LLVM/Flang"
    env: COMP="llvm"

script: ./compile-basecamp.sh $COMP
