name: "Continuous integration"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted

    steps:

      # Checkout the repo
      - uses: actions/checkout@v2

      # Build the code
      - run: ./compile-basecamp.sh ${{ inputs.compiler }} > ${{ outputs.logfile }} 2>&1
