name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: self-hosted

    steps:

      # Check out repo
      - uses: actions/checkout@v2

      # Build the code with GCC
     - id: build-gcc
       uses: wyphan/exciting-plus-gpu
         with:
           compiler: 'gcc'
           logfile: 'test-build-gcc.log'
       name: "Build Exciting-Plus with GCC"
       shell: bash
       run: ./compile-basecamp.sh gcc > ${{ outputs.logfile }} 2>&1

      # Build the code with AOCC/Flang
     - id: build-aocc
       uses: wyphan/exciting-plus-gpu
         with:
           compiler: 'llvm'
           logfile: 'test-build-aocc.log'
        name: "Build Exciting-Plus with AOCC"
        shell: bash
        run: ./compile-basecamp.sh llvm > ${{ outputs.logfile }} 2>&1
