name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: self-hosted

    steps:

      # Check out repo
      - uses: actions/checkout@v2

      # Build the code with GCC
      - uses: wyphan/exciting-plus-gpu
        with:
          compiler: 'gcc'
          logfile: 'test-build-gcc.log'
      - id: build-gcc
        name: "Build Exciting-Plus with GCC"
        shell: bash
        run: ./compile-basecamp.sh ${{ inputs.compiler }} > ${{ outputs.logfile }} 2>&1

      # Build the code with AOCC/Flang
      - uses: wyphan/exciting-plus-gpu
        with:
          compiler: 'llvm'
          logfile: 'test-build-aocc.log'
      - id: build-gcc
        name: "Build Exciting-Plus with AOCC"
        shell: bash
        run: ./compile-basecamp.sh ${{ inputs.compiler }} > ${{ outputs.logfile }} 2>&1
